// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoq9YcwcroKd6FbrXosrlFlWx6NQceqEQ',
    appId: '1:927724358502:web:95d051ec5381cceb5cd6a7',
    messagingSenderId: '927724358502',
    projectId: 'mynotes-25811',
    authDomain: 'mynotes-25811.firebaseapp.com',
    storageBucket: 'mynotes-25811.appspot.com',
    measurementId: 'G-CW1PK9T8MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMQzdY27K81f3zhx51PBuJFqlrHYLsnY',
    appId: '1:927724358502:android:f5457ab81c6efdf55cd6a7',
    messagingSenderId: '927724358502',
    projectId: 'mynotes-25811',
    storageBucket: 'mynotes-25811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1YtuBkB8lAj-nO08AmWWSLHfmKD3i88',
    appId: '1:927724358502:ios:f225091306c402935cd6a7',
    messagingSenderId: '927724358502',
    projectId: 'mynotes-25811',
    storageBucket: 'mynotes-25811.appspot.com',
    iosClientId: '927724358502-3lhk59l9a4dqs0oj0gkls3s37vihtj2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
